### ISSUE TITLE
Kodi 20.2 titan vanilla widgets 

### ISSUE THREAD

**Issue by Mushonov** [malvinas2/repository.vanilla20_old#1]
First i love this skin, but he didn't let me create widgets I'm mean it creates but not showing, long story short widgets don't work in 20.2, please fix this, and if you can add RTL to home screen menu 🙏🙏

**Comment by malvinas2** [comment]
What exactly do you mean by RTL support in the home screen, can you possibly take a screenshot?
In Marcel's original skin, RTL was rudimentarily supported, but only in two completely unimportant places that I deleted. As far as I know, the complete skin in RTL never existed.
(I answered your other questions in the forum, please have a look there)

**Comment by Mushonov** [comment]
> What exactly do you mean by RTL support in the home screen, can you possibly take a screenshot? In Marcel's original skin, RTL was rudimentarily supported, but only in two completely unimportant places that I deleted. As far as I know, the complete skin in RTL never existed. As mentioned in the forum I don't use widgets myself and have absolutely no idea how to create them. If anyone would like/can support here, any help is welcome.

i send you pictures in the form

**Comment by malvinas2** [comment]
Widgets have been updated, see new repo [https://github.com/malvinas2/repository.vanilla20](https://github.com/malvinas2/repository.vanilla20)

RTL Layout will not be added by my side.
